name: re_ucm_workspace
description: ""
publish_to: none

environment:
  sdk: ^3.12.0

workspace:
  - re_ucm_app
  - re_ucm_author_today
  - re_ucm_core
  - re_ucm_lib
  - re_ucm_ficbook

dependency_overrides:
  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      path: flutter_inappwebview
  dart_book:
    git:
      url: https://github.com/BooksFine/dart_book.git
      ref: v0.2.1
  xml: ^7.0.1

