name: zikzak_share_handler_windows
description: Windows stub implementation of zikzak_share_handler
version: 1.0.1
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  zikzak_share_handler_platform_interface: ^1.0.0

flutter:
  plugin:
    implements: zikzak_share_handler
    platforms:
      windows:
        dartPluginClass: ZikzakShareHandlerWindows
