targets:
  $default:
    builders:
      source_gen|combining_builder:
        # Оптимизация скорости генерации
        generate_for:
          include:
            - lib/**.cg.dart
        # Изменение пути вывода
        options:
          build_extensions:
            "^lib/{{}}.dart": "lib/.gen/{{}}.g.dart"
      mobx_codegen:mobx_generator:
        generate_for:
          include:
            - lib/**.cg.dart
      json_serializable:
        generate_for:
          include:
            - lib/**.cg.dart

