targets:
  $default:
    builders:
      source_gen|combining_builder:
        # Оптимизация скорости генерации
        generate_for:
          include:
            - lib/**.cg.dart
        # Изменение пути вывода
        options:
          build_extensions:
            "^lib/{{}}.dart": "lib/.gen/{{}}.g.dart"
      dart_mappable_builder:
        # Оптимизация скорости генерации
        generate_for:
          include:
            - lib/**.cg.dart
        # Изменение пути вывода
        options:
          build_extensions:
            "^lib/{{}}.dart": "lib/.gen/{{}}.mapper.dart"
      # chopper_generator|chopper_generator:
      #   # Оптимизация скорости генерации
      #   generate_for:
      #     include:
      #       - lib/**.cg.dart
      #   # Изменение пути вывода
      #   options:
      #     build_extensions:
      #       "^lib/{{}}.dart": "lib/.gen/{{}}.chopper.dart"
