targets:
  $default:
    builders:
      source_gen|combining_builder:
        # Оптимизация скорости генерации
        generate_for:
          include:
            - lib/**.cg.dart
        # Изменение пути вывода
        options:
          build_extensions:
            "^lib/{{}}.dart": "lib/.gen/{{}}.g.dart"

builders:
  changelog_builder:
    import: "package:re_ucm/features/changelog/changelog_builder.dart"
    builder_factories: ["changelogBuilder"]
    build_extensions: {"CHANGELOG.md": ["lib/.gen/features/changelog/changelog.gen.dart"]}
    auto_apply: root_package
    build_to: source
